### ISSUE TITLE
Can we use Github Pages?

### ISSUE THREAD

**Issue by si** [multipack/website#28]
Rather than self-host, it will probably make sense to use Github Pages with a CNAME for the domain. 

This is to simply see how it might work.

**Comment by si** [comment]
I've just renewed multipack.co.uk for another year and pointed a CNAME record to multipack.github.io so now it's loading the root README.

How can we configure it to use the __multipack_ directory? Maybe @tgvashworth can remember…

**Comment by dracos** [comment]
https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll says source is always overridden to be the top level; you can choose to serve from gh-pages, master, or the docs subdirectory, but I think that's it.

**Comment by si** [comment]
Thanks @dracos. Probably sensible to move to a different Jekyll framework if that's the case.

**Comment by trovster** [comment]
I have stripped back the code to get a functioning website. I have removed the Lanyard integration as that site has gone the way of the dodo. I have also removed the sign-up form, the social media icons and Twitter integration. I have added a quick HTML scrapper which will generate a static version of the site. This static version can be deployed to GitHub pages.

I have switched the settings to the gh-pages branch.

@si Let me know if this works for you. @multipack/contributors

**Comment by si** [comment]
Nice work @trovster! 
You've done much more than was expected. I wasn't sure if there was a quick win but I really appreciate the effort to get something up and running again. 
I'll give it a proper test this week and see how it goes. I'll probably try to fix any issues myself too as I've not touched code for so long. 

On a side note, speaking to Sam Hardacre the other day, it would be great to get the old gang together somehow. Either a one-off reunion or a revived format. I'm actually recording a new podcast series chatting with techies balancing work with life which might be an alternative way to catch up.
