### ISSUE TITLE
Integrate Github actions to deploy the site.

### ISSUE THREAD

**Issue by trovster** [multipack/website#31]
There are some GitHub action templates that use node which could be integated. This would save having to manually deploy the site and would be done on *push* to the master branch.

**Comment by trovster** [comment]
@si @paulrobertlloyd Please could you make an edit to a file and merge in to *master*… this should then (eventually) automatically appear on the live website.

**Comment by trovster** [comment]
On a recent deployment, I get 404 from GitHub, then it eventually works. You can check the change has been made by visiting http://multipack.github.io/website/ but be aware the CSS/JS doesn't work because of a sub-folder.

**Comment by si** [comment]
Sorry @trovster - just seen your messages.
Let me try an update to through develop to master and see what happens.

**Comment by trovster** [comment]
I can see the photo on the London page, so guess it has deployed. Three actions have been made with your merges, so I assume this is working.
